MOUSEKEY_ENABLE = no     # Mouse keys
RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = yes    # Enable WS2812 RGB underlight.
VIA_ENABLE      = yes    # Enable VIA
OLED_ENABLE     = yes
LTO_ENABLE      = yes
WPM_ENABLE = yes
AUTO_SHIFT_ENABLE = yes
LEADER_ENABLE = yes
